config/routes.rb
Rails.application.routes.draw do
 
 devise_for :users

 get "posts/search", to: "posts#search"

 resources :posts do
 	get "pdf",to: "posts#get_pdf"
 	resources :likes, only: [:create,:destroy]
 	resources :comments
 end

 root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes , dependent: :destroy

	validates :title,:content, presence: true

	validates :content, length: { minimum: 30 }

	def make_pdf

		Prawn::Document.new do |pdf|
			pdf.text " <strong>#{title}</strong> <br> #{content} ",:inline_format=>true
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	before_action :authenticate_user!,:correct_user? , only: [:edit,:update,:destroy]


	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id if current_user  # Assign a owner user to the comment if a current user exixts
															# without user_id the comment wont save

		if @comment.save
			redirect_to post_path(@post) , notice: "successfully posted comment" 
		else
			redirect_to post_path(@post) , notice: "Failed to post comment, comment cannot be blank" 
		end
	end

	def edit
		#@post = Post.find(params[:post_id])
		#@comment = @post.comments.find(params[:id])
	end

	def update
		#@post = Post.find(params[:post_id])
		#@comment = @post.comments.find(params[:id])

		if @comment.update(comment_params)
			redirect_to post_path(@post), notice: "Comment was updated"
		else
			render "edit"
		end
	end



	def destroy
		#@post = Post.find(params[:post_id])
		#@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to @post, notice: "The comment was deleted"
	end

	private

	def comment_params
		params.require("comment").permit(:comment)
	end

	def correct_user?
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if current_user.id != @comment.user_id
			redirect_to posts_path(@post), notice: "You cannot change others comments"
		end

	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@like = Like.new
		@like.user_id = current_user.id
		@like.post_id = @post.id

		if @like.save
			redirect_to post_path(@post), notice: "Liked post"
		else
			redirect_to post_path(@post), notice: "Failed to like post"
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@like = Like.find_by( post_id: @post.id , user_id: current_user.id )

		if @like
			@like.destroy
			redirect_to post_path(@post), notice: "Unliked post"
		else
			redirect_to post_path(@post), notice: "Cannot unlike post"
		end

	end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show,:edit,:update,:destroy]

	before_action :authenticate_user!, except: [:index,:show,:search]

	before_action :correct_user?, only: [:edit,:update,:destroy]

	def index
		@posts = Post.all.order("created_at desc")
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render "new"
		end

	end

	def show
	end

	def edit
	end

	def update

		if @post.update(post_params)
			redirect_to @post
		else
			render "edit"
		end
	end

	def destroy
		@post.destroy

		redirect_to root_path
	end

	def get_pdf
		@post = Post.find(params[:post_id])
		send_data @post.make_pdf.render,filename: "#{@post.title}.pdf",type: "application/pdf"
	end

	def search
		regexp = Regexp.new(params[:search],"i")

		@matches = []

		Post.all.each do |post|

			if post.title.match(regexp) or post.user.name.match(regexp)
				@matches<<post
			end
		end

	end

	private

	def post_params
		params.require(:post).permit(:title,:content)
	end

	def find_post
		@post = Post.find(params[:id])
	end

	def correct_user?
		find_post

		if current_user.id != @post.user_id
			redirect_to posts_path(@post), notice: "You cannot change others posts"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class = "content"><%= comment.comment %></p>
	<p class = "user"><%= comment.user.email %></p>
	<% if current_user and current_user.id == comment.user_id %>
		<p class = "buttons">
			<%= link_to "Delete", post_comment_path(comment.post,comment),method: :delete , data: {confirm: "are you sure ?" }%>

			<%= link_to "Edit", edit_post_comment_path(comment.post,comment)%>	
		</p>
	<% end %>
</div>
<HR>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment , placeholder: "Write your comment here..."%>
	</p>
	<p>
		<%= f.submit "Create comment"%> 
	</p>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment </h1>

<%= form_for [@post,@comment] do |f| %>
	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment , placeholder: "Write your comment here..."%>
	</p>
	<p>
		<%= f.submit "Update comment"%> 
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arp's Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lato:300,400,700' %>
    <%= stylesheet_link_tag 'application', 'http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main_header clearfix">
      <div class="wrapper">
        <div id="logo">
          <%= link_to "Arp's Forum", root_path %>
          <% if current_user %>
            <p> Signed in as <strong> <%= current_user.name %>, </strong> 
                <%= current_user.email %> 
            </p>
          <% end %>
        </div>
        <div id="buttons">
          <% if user_signed_in? %>
            <%= link_to "New Post", new_post_path %>
            <%= link_to "Edit Profile", edit_user_registration_path %>
            <%= link_to "Sign Out", destroy_user_session_path , method: :delete %> 
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path%> 
            <%= link_to "Sign in", new_user_session_path%> 
          <% end %>
        </div>
      </div>
    </header>
    <div class="wrapper">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<%= pluralize(@post.errors.count,"error") %> prevented this post from being saved.
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>


<%= form_for @post do |f| %>
	
	<p>
		<%= f.label :title%><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/_post.html.erb
<h2 class="title">
	<%= link_to post.title, post %>
</h2>

<p class="date">
	Published <%= time_ago_in_words(post.created_at) %> Ago by 
</p>

<p>
	<%=post.user.name %>
</p>

app/views/posts/_search_form.html.erb
<h2> Search Posts </h2>
<%= form_tag("posts/search",:method=>"get") do %>
	<p>
		<%= text_field_tag :search , nil, :required => true %>
	</p>
	<%= submit_tag "Search !" %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit post </h1>

<%= render "form" %>

<%=link_to "Cancel", post_path %>

app/views/posts/index.html.erb
<h1> Index </h1>

<%= render "search_form" %> 

<%= render @posts %>

app/views/posts/new.html.erb
<h1> New post</h1>

<%= render "form" %>

app/views/posts/search.html.erb
<h1> Search Results </h1>

<h2> <%= @matches.size %> matching search results  </h2>

<% @matches.each do |post| %>
	<%= render post%>
<% end %>

<br>

<%= link_to "Home",root_path %>

app/views/posts/show.html.erb
<div id="post_content">
	<h1> <%= @post.title %> </h1>

	<p> Author: <strong> <%= @post.user.name %> </strong> </p>

	<p> <%= @post.content %> </p>

	<p>
		<strong><%= pluralize(@post.likes.count,"like") %> </strong> for this post
		<br> 
		<% if current_user %>

			<% flag = @post.likes.any? do |like| %>
				<% like.user_id == current_user.id %>
			<% end %>

			<% unless  flag %>
				<%= link_to "Like", post_likes_path(@post), method: :post  %>
			<% else %>
				<%= link_to "Unlike", post_like_path(@post), method: :delete %>
			<% end %>

		<% end %>
	</p>

	<p> 
		<%= link_to "Get pdf", post_pdf_path(@post) %>
		<% if current_user and current_user.id == @post.user_id %>
			<%= link_to "Edit", edit_post_path(@post) %>
			<%= link_to "Destroy", post_path(@post), method: :delete , data: { confirm: "Are you sure ?" } %>
		<% end %>
		<%= link_to "Home", root_path(@post) %>
	</p>


	<div id="comments">
		<h2> <%= @post.comments.count %> comments for this post</h2>
	</div>

	<%= render @post.comments.order("created_at desc") %>

	<% if current_user %>
		<h3>
			Reply to thread
			<%= render "comments/form" %>
		</h3>
	<% end %>
</div>